import localFont from "next/font/local";
import "./globals.css";
<<<<<<< HEAD
import Myastroredux from "@/lib/Myastroredux";
=======
>>>>>>> 3b3788d3aa9b7a9314d0b902fa80e405dd5a6bf6

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
<<<<<<< HEAD
  title: "Best Astrology App | Myastro",
  description: "Best Astrology App",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 3b3788d3aa9b7a9314d0b902fa80e405dd5a6bf6
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
        <Myastroredux>{children}</Myastroredux>
=======
        {children}
>>>>>>> 3b3788d3aa9b7a9314d0b902fa80e405dd5a6bf6
      </body>
    </html>
  );
}
