const zodiacData = [
    {
      name: 'Aries',
      image: '/horoscope-icon/Aries.jpg',
      luckyColors: 'Red, White',
      luckyNumbers: '1, 9',
      luckyAlphabets: 'A, L',
      description: 'Aries is known for its fiery energy, leadership, and determination.',
    },
    {
      name: 'Taurus',
      image: '/taurus.jpg',
      luckyColors: 'Green, Pink',
      luckyNumbers: '2, 6',
      luckyAlphabets: 'B, V',
      description: 'Taurus is grounded, patient, and enjoys the finer things in life.',
    },
    {
      name: 'Gemini',
      image: '/gemini.jpg',
      luckyColors: 'Yellow, Blue',
      luckyNumbers: '3, 5',
      luckyAlphabets: 'C, K',
      description: 'Gemini is curious, adaptable, and loves communication.',
    },
    {
      name: 'Cancer',
      image: '/cancer.jpg',
      luckyColors: 'White, Silver',
      luckyNumbers: '2, 7',
      luckyAlphabets: 'D, H',
      description: 'Cancer is emotional, nurturing, and values home and family.',
    },
    {
      name: 'Leo',
      image: '/leo.jpg',
      luckyColors: 'Gold, Orange',
      luckyNumbers: '1, 4',
      luckyAlphabets: 'E, M',
      description: 'Leo is confident, passionate, and loves to be in the spotlight.',
    },
    {
      name: 'Virgo',
      image: '/virgo.jpg',
      luckyColors: 'Green, Brown',
      luckyNumbers: '5, 8',
      luckyAlphabets: 'F, R',
      description: 'Virgo is analytical, detail-oriented, and values cleanliness and order.',
    },
    {
      name: 'Libra',
      image: '/libra.jpg',
      luckyColors: 'Pink, Blue',
      luckyNumbers: '6, 9',
      luckyAlphabets: 'G, S',
      description: 'Libra values balance, harmony, and is known for their diplomacy.',
    },
    {
      name: 'Scorpio',
      image: '/scorpio.jpg',
      luckyColors: 'Red, Black',
      luckyNumbers: '2, 8',
      luckyAlphabets: 'H, Z',
      description: 'Scorpio is intense, mysterious, and deeply emotional.',
    },
    {
      name: 'Sagittarius',
      image: '/sagittarius.jpg',
      luckyColors: 'Purple, Yellow',
      luckyNumbers: '3, 7',
      luckyAlphabets: 'I, T',
      description: 'Sagittarius is adventurous, optimistic, and loves freedom.',
    },
    {
      name: 'Capricorn',
      image: '/capricorn.jpg',
      luckyColors: 'Brown, Grey',
      luckyNumbers: '4, 8',
      luckyAlphabets: 'J, K',
      description: 'Capricorn is disciplined, ambitious, and values tradition.',
    },
    {
      name: 'Aquarius',
      image: '/aquarius.jpg',
      luckyColors: 'Blue, Silver',
      luckyNumbers: '2, 9',
      luckyAlphabets: 'L, U',
      description: 'Aquarius is innovative, independent, and loves social causes.',
    },
    {
      name: 'Pisces',
      image: '/pisces.jpg',
      luckyColors: 'Sea Green, Lavender',
      luckyNumbers: '3, 7',
      luckyAlphabets: 'M, P',
      description: 'Pisces is empathetic, creative, and deeply intuitive.',
    },
  ];
  
  export default zodiacData;
  